apiVersion: v1
kind: Service
metadata:
  labels:
    app: news-frontend
  name: news-frontend
  #namespace: admin-che
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 31111
  selector:
    app: news-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-frontend
  #namespace: admin-che
  labels:
    app: news-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-frontend
  template:
    metadata:
      labels:
        app: news-frontend
    spec:
      containers:
        - env:
            - name: NODE_PORT
              value: "8081"
            - name: NODE_IP
              value: "34.95.34.124"
          image: us.gcr.io/graphite-sphere-362322/news-frontend
          name: news-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80