apiVersion: v1
kind: Service
metadata:
  labels:
    app: news-backend
  name: news-backend
  #namespace: admin-che
spec:
  #type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 30000
  selector:
    app: news-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-backend
  #namespace: admin-che
  labels:
    app: news-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-backend
  template:
    metadata:
      labels:
        app: news-backend
    spec:
      containers:
        - env:
            - name: backend.nlp.url
              value: http://location-extractor:8081/get_loc
            - name: quarkus.datasource.jdbc.url
              value: jdbc:postgresql://postgis:5400/news?user=postgres&password=banane
          image: us.gcr.io/graphite-sphere-362322/news-backend
          name: news-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080